name: dadata
description: DaData.ru Suggestions API implementation (address suggestions, reverse geocoding)
version: 0.3.3
repository: https://github.com/darkxanter/dadata_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
