name: dadata
description: Dadata Suggestions for Dart
version: 0.3.1
repository: https://github.com/darkxanter/dadata_flutter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  lints: ^2.0.0
  mockito: ^5.1.0
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
