name: dadata
description: Dadata address suggestions (including forward and reverse geocoding) for Flutter.
version: 0.2.1
repository: https://github.com/darkxanter/dadata_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
